# Generated by Django 4.1.5 on 2023-01-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickerLeaderboard',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GalagaLeaderboard',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SnakeLeaderboard',
            fields=[
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
