# Generated by Django 4.1.5 on 2023-01-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckgame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snakeScore', models.DecimalField(decimal_places=10, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='UserScores',
        ),
    ]
