# Generated by Django 4.1.5 on 2023-01-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duckgame', '0002_userscore_delete_userscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='snakeScore',
            field=models.IntegerField(),
        ),
    ]
